# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.AlterModelOptions(
            name='homeskills',
            options={'verbose_name': 'Home Skill', 'verbose_name_plural': 'Home Skills'},
        ),
    ]
