# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academic_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_topic', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
    ]
