# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=1000)),
                ('tech', models.CharField(max_length=10000, verbose_name='Technology Stack Used')),
                ('description', models.TextField()),
            ],
        ),
    ]
