# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
