# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='address',
            field=models.TextField(),
        ),
    ]
