# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170909_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('profile_text', models.TextField()),
                ('skill_text', models.TextField()),
                ('certification_text', models.TextField()),
            ],
        ),
    ]
