# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_abouttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('profile_text', models.TextField()),
                ('skill_text', models.TextField()),
                ('certification_text', models.TextField()),
                ('contact_text', models.TextField()),
                ('resume_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutText',
        ),
    ]
