# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_misctext_profilepic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='certificate',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
