# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workexperience_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='marksheet',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='certificate',
            field=models.CharField(max_length=10000, verbose_name=b'Certificate Link (google drive)'),
        ),
    ]
