# Generated by Django 2.0.1 on 2018-01-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170925_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='certificate',
            field=models.CharField(max_length=10000, verbose_name='Certificate Link (google drive)'),
        ),
    ]
